// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByC9MRE91ERS_YlGT2KiZ3AhD9zmhDJ-k',
    appId: '1:646313047712:web:f6f4e6ef3cdc96cc883bc5',
    messagingSenderId: '646313047712',
    projectId: 'form-app-28a2d',
    authDomain: 'form-app-28a2d.firebaseapp.com',
    storageBucket: 'form-app-28a2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADoF8Btff7L8RxEs65ZwECyRb0GT1NfP4',
    appId: '1:646313047712:android:c47604d67b5476ed883bc5',
    messagingSenderId: '646313047712',
    projectId: 'form-app-28a2d',
    storageBucket: 'form-app-28a2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_jLxQ8s8SK_yHicZDwFpucAVq1LXjanM',
    appId: '1:646313047712:ios:d6bc03ad18eb9b5c883bc5',
    messagingSenderId: '646313047712',
    projectId: 'form-app-28a2d',
    storageBucket: 'form-app-28a2d.firebasestorage.app',
    iosBundleId: 'com.example.formApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_jLxQ8s8SK_yHicZDwFpucAVq1LXjanM',
    appId: '1:646313047712:ios:d6bc03ad18eb9b5c883bc5',
    messagingSenderId: '646313047712',
    projectId: 'form-app-28a2d',
    storageBucket: 'form-app-28a2d.firebasestorage.app',
    iosBundleId: 'com.example.formApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByC9MRE91ERS_YlGT2KiZ3AhD9zmhDJ-k',
    appId: '1:646313047712:web:ce7490c409c82ee4883bc5',
    messagingSenderId: '646313047712',
    projectId: 'form-app-28a2d',
    authDomain: 'form-app-28a2d.firebaseapp.com',
    storageBucket: 'form-app-28a2d.firebasestorage.app',
  );
}
